name: Create Tag

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Tag
        run: |
          PACKAGE_VERSION=$(jq -r '.version' package.json)
          git tag "$PACKAGE_VERSION"
          git push --tags
